--- Makefile
+++ Makefile
@@ -8,7 +8,7 @@ all: herbe
 config.h: config.def.h
 	cp config.def.h config.h
 
-herbe: herbe.c config.h
+herbe: herbe.c config.h Makefile
 	$(CC) herbe.c $(CFLAGS) -o herbe
 
 install: herbe
